/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prjguis1;

import javax.swing.JOptionPane;

/**
 *
 * @author keaga
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discountGroup = new javax.swing.ButtonGroup();
        checkbox1 = new java.awt.Checkbox();
        jRadioButton1 = new javax.swing.JRadioButton();
        lblHeading = new javax.swing.JLabel();
        lblProdld = new javax.swing.JLabel();
        lblProdName = new javax.swing.JLabel();
        lblProdPrice = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        txtInputId = new javax.swing.JTextField();
        txtInputName = new javax.swing.JTextField();
        txtInputPrice = new javax.swing.JTextField();
        optYes = new javax.swing.JRadioButton();
        optNo = new javax.swing.JRadioButton();
        lblInsurance = new javax.swing.JLabel();
        chkInsurance = new javax.swing.JCheckBox();
        btnProcess = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        checkbox1.setLabel("checkbox1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeading.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lblHeading.setText("Products Form");

        lblProdld.setText("Product ID:");

        lblProdName.setText("Product Name:");

        lblProdPrice.setText("Product Price:");

        lblDiscount.setText("DISCOUNT:");

        discountGroup.add(optYes);
        optYes.setText("Yes");
        optYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optYesActionPerformed(evt);
            }
        });

        discountGroup.add(optNo);
        optNo.setText("No");

        lblInsurance.setText("Insurance:");

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblProdld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblProdName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(lblProdPrice)
                                .addComponent(lblDiscount)
                                .addComponent(lblInsurance))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optNo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtInputId, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(txtInputName)
                                .addComponent(txtInputPrice)
                                .addComponent(optYes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblHeading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdld)
                    .addComponent(txtInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdName)
                    .addComponent(txtInputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdPrice)
                    .addComponent(txtInputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiscount)
                    .addComponent(optYes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsurance)
                    .addComponent(chkInsurance))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        try{
            String strId , strName, strInsurance, strDsiplay;
            double dblPrice=0.0, dblDiscount = 0;
            boolean blnDiscount = false;
            
            strId = this.txtInputId.getText();
            strName = this.txtInputName.getText();
            dblPrice = Double.parseDouble(this.txtInputPrice.getText());
            
            if (this.optYes.isSelected()){
                dblDiscount=dblPrice * 10/100;
                blnDiscount = true;
            }
            if (this.optNo.isSelected()){ 
                dblDiscount=0.0;
                blnDiscount=true;
            }
            if (blnDiscount == false){
                JOptionPane.showMessageDialog(null, "Please select a discount option");
                return;
                
            }
            
            if(this.chkInsurance.isSelected()){
                strInsurance = "YES";
                dblPrice += 100;
            }
            else{
                strInsurance="NO";
            }
            
            strDsiplay = "Product invoice\n\n" +
                    "Product ID: " + strId + "\n" +
                    "Procuct Name: " + strName  +"\n" +
                    "Product Price: " + dblPrice + "\n"+
                    "Discount: " + dblDiscount + "\n" +
                    "Total Amount: " + (dblPrice - dblDiscount) + "\n"+
                   "Insurance: " + strInsurance;
                    JOptionPane.showMessageDialog(null, strDsiplay);
                    
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
        this.txtInputId.setText("");
        this.txtInputName.setText("");
        this.txtInputPrice.setText("");
        this.discountGroup.clearSelection();
        this.chkInsurance.setSelected(false);
        
        
        
        
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
       int intConfirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit the program?", "Ëxit program messagebox" , JOptionPane.YES_NO_OPTION);
       if (intConfirmed == JOptionPane.YES_NO_OPTION){
           System.exit(0);
       }
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void optYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optYesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnProcess;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JCheckBox chkInsurance;
    private javax.swing.ButtonGroup discountGroup;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JLabel lblProdPrice;
    private javax.swing.JLabel lblProdld;
    private javax.swing.JRadioButton optNo;
    private javax.swing.JRadioButton optYes;
    private javax.swing.JTextField txtInputId;
    private javax.swing.JTextField txtInputName;
    private javax.swing.JTextField txtInputPrice;
    // End of variables declaration//GEN-END:variables
}
