/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prjexamprep3;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lab_services_student
 */
public class frmMain extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMain.class.getName());
    // arraylists will be used to load from text file into the array list
    private ArrayList snakeName = new ArrayList();
    private ArrayList fatality = new ArrayList();
    private ArrayList medical = new ArrayList();

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        callSnakes(); // load snake names from text file into combo box
        loadSnakes(); // load all snake information from the text file into array lists
        
    }

    private void callSnakes() {
      
        // only if load from text file
        try (BufferedReader br = new BufferedReader(new FileReader("snakes.txt"))) {
            String line;
            int lineCount = 0;
            int nextTarget = 1; // start from the first line

            while ((line = br.readLine()) != null) {
                lineCount++;

                if (lineCount == nextTarget) {
                    cmbSnake.addItem(line.trim());
                    nextTarget += 3; // then every 3rd line after that
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error reading file: " + ex.getMessage(),
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // can put values into combo box like below
    /*this.cbSnakes.addItem("Black Mamba");
        this.cbSnakes.addItem("Boomslang");
        this.cbSnakes.addItem("Puff Adder");*/
    private void searchSnakes() {

        int intSelect = this.cmbSnake.getSelectedIndex();

        if (intSelect >= 0 && intSelect < snakeName.size()) {

            DefaultListModel<String> model = new DefaultListModel<>(); // needed for list box

            model.addElement("Snake Name: " + snakeName.get(intSelect)); // add to list 

            model.addElement(fatality.get(intSelect).toString());

            model.addElement(medical.get(intSelect).toString());

            lstDisplay.setModel(model); // display list in list box

        }

    }

    private void loadSnakes() {

        try {
            String strCurrentLine;
            BufferedReader br = new BufferedReader(new FileReader("snakes.txt"));
            while ((strCurrentLine = br.readLine()) != null) {
                snakeName.add(strCurrentLine); // reads each line and saves from text file into arraylist
                strCurrentLine = br.readLine();
                fatality.add(strCurrentLine);
                strCurrentLine = br.readLine();
                medical.add(strCurrentLine);
            }
            br.close();
        } catch (IOException ex) {
            System.out.println("The following error occured: ");
            ex.toString();
        }
    }

    private void clear() {

        this.cmbSnake.setSelectedIndex(0);

        lstDisplay.setModel(new DefaultListModel<>()); // clear the list box

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSnake = new javax.swing.JLabel();
        btnProcess = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDisplay = new javax.swing.JList<>();
        cmbSnake = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSnake.setText("Select snake:");

        btnProcess.setText("PROCESS");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstDisplay);

        cmbSnake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSnakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSnake, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcess))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClear)
                            .addComponent(cmbSnake, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSnake)
                    .addComponent(cmbSnake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcess)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        searchSnakes(); // based on combo box selection, find snake information to display

        

    }//GEN-LAST:event_btnProcessActionPerformed

    private void cmbSnakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSnakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSnakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnProcess;
    private javax.swing.JComboBox<String> cmbSnake;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSnake;
    private javax.swing.JList<String> lstDisplay;
    // End of variables declaration//GEN-END:variables
}
