/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prjgui3;

import javax.swing.DefaultListModel;

/**
 *
 * @author keaga
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        this.setLocationRelativeTo(null); //sets form to middle of screen when running
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        cmbPhone = new javax.swing.JComboBox<>();
        btnOk = new javax.swing.JButton();
        scrollPhones = new javax.swing.JScrollPane();
        lstPhones = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeading.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHeading.setText("COMPARE CELLPHONES");

        lblPhone.setText("Select Phone:");

        cmbPhone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samsung", "Iphone", "Hauweii", " " }));
        cmbPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPhoneActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        scrollPhones.setViewportView(lstPhones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPhones)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblHeading)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHeading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(cmbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk))
                .addGap(41, 41, 41)
                .addComponent(scrollPhones, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        
        if(this.cmbPhone.getSelectedIndex() == 0){
            samsung();
            
        }
        
        if(this.cmbPhone.getSelectedIndex()==1){
            Iphone();
        }
        if(this.cmbPhone.getSelectedIndex()==2){
            Hauweii();
        }
   
    }//GEN-LAST:event_btnOkActionPerformed

    private void cmbPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPhoneActionPerformed

    private void samsung(){
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("MAKE: SAMSUNG");
        listModel.addElement("Model: s25");
        listModel.addElement("Price: R18 999");
        listModel.addElement("MAKE: SAMSUNG");
        listModel.addElement("Model: s25");
        listModel.addElement("Price: R18 999");
        listModel.addElement("MAKE: SAMSUNG");
        listModel.addElement("Model: s25");
        listModel.addElement("Price: R18 999");
        listModel.addElement("MAKE: SAMSUNG");
        listModel.addElement("Model: s25");
        listModel.addElement("Price: R18 999");
        listModel.addElement("MAKE: SAMSUNG");
        listModel.addElement("Model: s25");
        listModel.addElement("Price: R18 999");
        
        this.lstPhones.setModel(listModel);
    }
    
     private void Iphone(){
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("MAKE: Iphone");
        listModel.addElement("Model: I5");
        listModel.addElement("Price: R20 999");
        
        this.lstPhones.setModel(listModel);
    }
    
     
      private void Hauweii(){
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("MAKE: Hauwii");
        listModel.addElement("Model: H6");
        listModel.addElement("Price: R19 999");
        
        this.lstPhones.setModel(listModel);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cmbPhone;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JList<String> lstPhones;
    private javax.swing.JScrollPane scrollPhones;
    // End of variables declaration//GEN-END:variables
}
